stages:
  fetch_data:
    cmd: python airflow_pipeline\dags\src\scrape_data.py
    deps:
      - airflow_pipeline\dags\src\scrape_data.py
    outs:
      - datasets\data.csv
  process_data:
    cmd: python airflow_pipeline\dags\src\preprocessing.py
    deps:
      - airflow_pipeline\dags\src\preprocessing.py
      - datasets\data.csv
    outs:
      - datasets\processed_data.csv
  model_training:
    cmd: python src\training.py
    deps:
      - src\training.py
      - datasets\processed_data.csv
    outs:
      - models\model_final.pkl:
          cache: true
